version: '3.8'

services:
  backend:
    container_name: pokedex-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/src/app
    environment:
      - GO_ENV=${ENV}
    restart: unless-stopped

  frontend:
    container_name: pokedex-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${ENV}
    depends_on:
      - backend
    restart: unless-stopped